### PR TITLE
Add libs/context and libs/fiber

### PR DESCRIPTION
**Pull request by fuzhe1989**

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
LGTM. But maybe a clean up is needed. see: https://github.com/pingcap/tics/tree/master/contrib/boost-cmake

**Comment by fuzhe1989** [comment]
@SchrodingerZhu They will have separate cmake files.

**Comment by JaySon-Huang** [comment]
I think we can remove those files under doc/ and example/ ?

**Comment by fuzhe1989** [comment]
@JaySon-Huang @SchrodingerZhu updated.

**Review by JaySon-Huang — APPROVED** [review]

**Pull request merged**
